spring:
  datasource:
    url: jdbc:h2:mem:credit-application-system-db
    username: fabinho
    password: F#123456
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
